# Generated by Django 4.2 on 2026-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qwe',
        ),
    ]
